# Bash Tab Completion for Collection of Indv. Custom Aliases


## source external comp scripts
BASH_COMP_SCRIPTS_DIR="$HOME/git/dotfiles/bash.d/completers"
for compfile in $(find $BASH_COMP_SCRIPTS_DIR -type f); do 
  source $compfile
done

# tldr alias
complete -o filenames -F _shtab_tldr tt

# @BROKEN: Need to fix so behavior mirrors rg<tab>
# rg alias
#complete -F _rg -o bashdefault -o default rgi
complete -F _rg -o bashdefault -o default rgv

# cheat aliases 
complete -F _cheat c
complete -F _cheat cl
complete -F _cheat ce

# taskwarrior aliases
complete -o nospace -F _task t
complete -o nospace -F _task ta
complete -o nospace -F _task tl


# @BROKEN: Ripgrep and FD fzfcomp dont work. Need to revert to "python" __fzf_default_completion form.
# ripgrep alias
complete -o bashdefault -o default -F _fzf_path_completion rgi
complete -o bashdefault -o default -F _fzf_path_completion rgc
complete -o bashdefault -o default -F _fzf_path_completion rgl
complete -o bashdefault -o default -F _fzf_path_completion rgv
complete -o bashdefault -o default -F _fzf_path_completion rgo
complete -o bashdefault -o default -F _fzf_path_completion rgp
complete -o bashdefault -o default -F _fzf_path_completion rgl
complete -o bashdefault -o default -F _fzf_path_completion rg_bare

# fd aliases
complete -o bashdefault -o default -F _fzf_path_completion fdhi
complete -o bashdefault -o default -F _fzf_path_completion fdca
complete -o bashdefault -o default -F _fzf_path_completion fdcb
complete -o bashdefault -o default -F _fzf_path_completion fdcw
complete -o bashdefault -o default -F _fzf_path_completion fdt
complete -o bashdefault -o default -F _fzf_path_completion fde
complete -o bashdefault -o default -F _fzf_path_completion fda
complete -o bashdefault -o default -F _fzf_path_completion fdi


# @TODO
# python default arg comp for aliases
#complete -F __fzf_default_completion python
