# source rc/runtime config dirs

# set up non-root bins 
export GOPATH="$HOME/.local/share/applications/go"
GO_BIN="$GOPATH/bin"
export CARGO_BIN="$HOME/.cargo/bin"
export TOOLBOX_BIN="$HOME/.toolbox/bin"

# standard bins
export PATH=$HOME/.local/bin:/usr/local/bin:$PATH

# non-standard bins
export PATH=$GO_BIN:$CARGO_BIN:$TOOLBOX_BIN:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""

# CASE_SENSITIVE="true"
HYPHEN_INSENSITIVE="true"
HIST_STAMPS="yyyy-mm-dd"
zstyle ':omz:update' mode disabled  # disable automatic updates
# ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM="$HOME/dotfiles/zsh.d/custom"
export EDITOR=nvim

### ------------------------------
###   Plugins
### ------------------------------

## ZVM must be sourced BEFORE "plugins" and AUTOSUGGESTIONS/key binds must 
## come AFTER "plugins". FZF key bindings must be sourced AFTER 
## AUTOSUGGESTIONS key bindings

## Color hexcodes source: https://github.com/AlexvZyl/nordic.nvim/blob/main/assets/palette.png

##  ZSH-VI-MODE
ZVM_ESCAPE_KEYTIMEOUT=0.25        # escape key timeout default is 0.3
ZVM_VI_INSERT_ESCAPE_BINDKEY='^[b'  # <ALT>b switch from Insert to Normal  
ZVM_VI_VISUAL_ESCAPE_BINDKEY='^[v'  # <ALT>v switch from Insert to Visual
ZVM_VI_HIGHLIGHT_BACKGROUND="#60728A"   # prettier visual mode highlighting 

# plugins (has both custom and default ohmyzsh plugins)
plugins=(git colored-man-pages zsh-autosuggestions zsh-vi-mode git-extras tldr z zsh-syntax-highlighting)

## ZSH AUTOSUGGESTIONS (must set key bindings after ZVM)
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#60728A"    # gray5

# <Ctrl><Space> accepts and executes suggestion
bindkey '^ ' autosuggest-accept
# <Alt>x accepts but doesnt execute suggestion
bindkey '^[x' autosuggest-execute 

# <Alt>m acts like <RIGHT> arrow key and can partial accept suggestions
bindkey '^[m' forward-word

# <Alt>, clear suggestion
bindkey '^[,' autosuggest-clear

# source ohmyzsh for default behaviors
source $ZSH/oh-my-zsh.sh 

# User configuration
export MANPATH="/usr/local/man:$MANPATH"

# TODO: see if this can be factored out into submodule
# ========================================================================
# 	THEME
# ========================================================================

fpath+=(/home/nukk/dotfiles/zsh.d/custom/themes/pure)
autoload -U promptinit; promptinit

# options
PURE_GIT_PULL=0

# prompt configurations
# NORD FROST SHADES:  
#   #8fbcbb
#   #88c0d0
#   #81a1c1
#   #5e81ac

# non-git prompt components
zstyle :prompt:pure:host color '#81A1C1'
zstyle :prompt:pure:user color '#81A1C1'
zstyle :prompt:pure:path color '#81A1C1'
zstyle :prompt:pure:prompt:success color yellow
zstyle :prompt:pure:prompt:error color yellow

# git prompt components
zstyle :prompt:pure:git:action color green
#zstyle :prompt:pure:git:branch color '#9FC6C5'  # cyan
zstyle :prompt:pure:git:branch color '#B1C89D'  # green
zstyle :prompt:pure:git:dirty color red 
zstyle :prompt:pure:git:stash show yes
zstyle :prompt:pure:git:arrow color green
zstyle :prompt:pure:git:stash color yellow

prompt pure
# ========================================================================
# 	Functions
# ========================================================================

# vim
alias vim="/usr/bin/vim"
alias vi="/usr/bin/vim"

# neovim
alias nv="/usr/bin/nvim"
#alias nvim="$HOME/.local/bin/lvim"  # use lvim until nvim is operational

# lunarvim stable
alias lv="$HOME/.local/bin/lvim"
alias lvim="$HOME/.local/bin/lvim"

### ========================================
###     SOURCE DOTFILE CONFIG SUBMODULES
### ========================================

# runtime/shell-agnostic config files
source_runtime_configs(){
    DIRPATH="$HOME/dotfiles/rc.d"
    for x in $(find $DIRPATH -type f | egrep "\.rc$");
    do
        source "$x" && echo "$x sourced successfully"  

    done
}

source_shell_configs(){
    if [ "$(basename $SHELL)" = "zsh" ]; then 
        # add custom completions 
        ZSH_CUSTOM_COMPLETIONS="$ZSH_CUSTOM/completions"
        fpath=($ZSH_CUSTOM_COMPLETIONS \\$fpath)
        autoload -Uz compinit
        compinit
        echo "Added custom ZSH completions"

        # source custom zshrc configuration files
        for x in $(find "$HOME/dotfiles/zsh.d" -type f -name "*.zshrc" );
        do
            source "$x" && echo "$x" sourced successfully 
        done
    else
        # uncommenting since this clutters file atm
        #find "$HOME/dotfiles/bash.d" -type f | egrep "*.bashrc$" | xargs -I "{}" echo source {} && xargs -I "{}" "sourced {} succesfully" \;
        echo "Source bash-only files if exists"
    fi
    return 0
}


# source custom configuration files
source_runtime_configs > /dev/null 2>&1
source $ZSH_CUSTOM/patches/you-should-use-patch.zshrc > /dev/null 2>&1
source_shell_configs > /dev/null 2>&1

# NEEDSFIX: as of now the completions need to be sourced manually after
# everything is loaded at runtime. Also the command flag tab completion is
# broken.
# fzf 
source $HOME/dotfiles/rc.d/fzf.rc
source $HOME/dotfiles/config.d/fzf.config
source /usr/share/fzf/shell/key-bindings.zsh
source /usr/share/zsh/site-functions/fzf
# TEMPFIX: easier reloaded after shell initialized
fzz(){
    source /usr/share/fzf/shell/key-bindings.zsh
    #source /usr/share/zsh/site-functions/fzf
    source $XDG_BIN_HOME/fzf_completion.zsh

}
fzz
