#- hosts: all
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Update APT packages
      apt: update_cache=yes cache_valid_time=36000
    - name: Install APT packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - ansible-core
        - expect
        - make
        - nodejs
        - npm
        - plocate
        - python3
        - python3-pip
        - ripgrep
        - rlwrap
        - unzip
        # alacritty dependencies
        - cmake
        - g++
        - libfreetype6-dev
        - libfontconfig1-dev
        - libxcb-xfixes0-dev
        - libxkbcommon-dev
