---
all:
  # all "ungrouped" hosts go here
  hosts:
    shelby:
      ansible_host:
        138.197.175.90
  # all "grouped" hosts go here
  children:
    linode:
      hosts:
        newark1:
          ansible_host: 66.228.40.141
    digitalocean:
      hosts:
        ny3:
          ansible_host: 64.225.11.27
        syd1:
          ansible_host: 170.64.151.189
    dbservers:
      hosts:
        66.228.40.141: {}
        170.64.151.189: {}
