---
all:
  # all "ungrouped" hosts go here
  hosts:
    tlop:
      ansible_host:
        66.228.40.141
    localhost:
      ansible_host: 127.0.0.1

  # all "grouped" hosts go here
  children:
    linode:
      hosts:
        # aka. TLOP
        newark1:
          ansible_host: 66.228.40.141
    azure:
      hosts:
        azvm1:
          azureadmin1:
          ansible_host: 72.145.1.77
        azvm2:
          ansible_host: 72.145.9.114
