---
- hosts: all
  tasks:
    - name: Update APT packages
      apt: update_cache=yes cache_valid_time=36000

    - name: Install APT packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - rlwrap
        - ripgrep
        - make
        - python3-pip
        - python3
        - npm
        - nodejs
        - expect
        - unzip

- hosts: dbservers
  vars:
    fixture_name: usda.sql
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Copy MySQL fixture
      copy:
        src: "{{fixture_name}}"
        dest: "/opt/{{fixture_name}}"
