---
- hosts: localhost
  become: yes
  tasks:
    - name: Update APT packages
      apt: update_cache=yes cache_valid_time=36000

    - name: Install APT packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - rlwrap
        - ripgrep
        - make
        - python3-full
        - npm
        - nodejs
        - unzip
