#!/usr/bin/bash

# variables
DOTFILES_DIR="$HOME/dotfiles"
BASHD_DIR="$DOTFILES_DIR/bash.d"
VIMD_DIR="$DOTFILES_DIR/vim.d"
GITD_DIR="$DOTFILES_DIR/git.d"
TMUXD_DIR="$DOTFILES_DIR/tmux.d"


## XDG folders/export
mkdir -p "$HOME/.local/{bin,share,state,runtime,var,common}" && mkdir -p "$HOME/.{cache,config}"
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_COMMON_HOME="$HOME/.local/common"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"

# @TODO: Add logic for ZSH - currently only works handles bashrc
# check if current machine is WSL/LOCAL or REMOTE 
if [[ $(echo $(hostname) | egrep -ci "desktop") -ge 1 ]]; then
    echo "Local WSL machine"
    ln -srf "$BASHD_DIR/bashrc_wsl" "$HOME/.bashrc" 
else 
    echo "Remote machine - use standard bashrc"
    ln -sfr "$BASHD_DIR/bashrc" "$HOME/.bashrc"
fi


# symlink core files

## bash 
# @FIXME
find "$BASHD_DIR" -type f -name "*.bashrc" -or -name "*.completer" \
    -exec echo source {} \;

## git
ln -srf "$GITD_DIR/gitignore" "$HOME/.gitignore" 
ln -srf "$GITD_DIR/gitconfig" "$HOME/.gitconfig" 

## vim
ln -srf "$VIMD_DIR/vimrc" "$HOME/.vimrc" 

## tmux
# @TODO: Add cleaner logic for handling XDG_CONFIG setup/symlinking/overwriting existing symlinks
# tmux XDG_CONFIG dependency
mkdir -p $HOME/.config
#ln -srf "$TMUXD_DIR" "$HOME/.config/tmux" 
ln -sr "$TMUXD_DIR" "$HOME/.config/tmux" 
ln -srf "$TMUXD_DIR/tmux.conf" "$HOME/.tmux.conf" 
