#!/usr/bin/env bash

## Custom Functions Tab-Completion Awareness 

## Simple example to build off of

# Example Shell Usage: mycmd <TAB>  -->  <alpha, beta, gamma> appear as comp suggestions
_my_custom_completion() {
    COMPREPLY=($(compgen -W "alpha beta gamma" -- "${COMP_WORDS[1]}"))
}
complete -F _my_custom_completion mycmd


# custom function that populates all possible <Tab> completion options for
# my custom git diff aliases 
#
# -- still learning the ropes to this, so the "excepted" usage below is more of 
# -- a starting point/inital guess but is more than likely going to be modified
# -- in the future after inital debugging/testing chatgpt code
# Example Expected/Targeted Usage
_my_custom_completion_git_diff_aliases() {
    # populate git diff tab comp suggs from git branch all output
    g=$(git branch -la | awk -F '\t' '{print $NF}')
    declate GB_LIST
    for g in ${GBLA[@]}; do
        echo $g
        if [[ $(echo $g | egrep -c "^remotes") -ge 1 ]]; then
              # trim remotes prefix
            g=$(echo $g | egrep -o "origin.+$")
        fi
        # add <g> to <GB_LIST>
    done

    GBLA="$(git branch -la | awk -F '\t' '{print $NF}')"
    # expand git branch list in `compgen -W "<GBLA>"`  ## prob need more debugging
    COMPREPLY=($(compgen -W "$(GBLA)" -- "${COMP_WORDS[1]}"))
}
complete -F _my_custom_completion gd


